<?php
/**
 * MultiLanguageResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TestingTime Public API
 *
 * Partners API to recruit test users with TestingTime programmatically
 *
 * OpenAPI spec version: 1.1.0
 * Contact: api-support@testingtime.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiLanguageResponseTest Class Doc Comment
 *
 * @category    Class
 * @description A single response option for a user in all languages and if selecting this option brings a user further or gets rejected.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiLanguageResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiLanguageResponse"
     */
    public function testMultiLanguageResponse()
    {
    }

    /**
     * Test attribute "en"
     */
    public function testPropertyEn()
    {
    }

    /**
     * Test attribute "de"
     */
    public function testPropertyDe()
    {
    }

    /**
     * Test attribute "fr"
     */
    public function testPropertyFr()
    {
    }

    /**
     * Test attribute "qualification"
     */
    public function testPropertyQualification()
    {
    }
}
