<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TestingTime Public API
 *
 * Partners API to recruit test users with TestingTime programmatically
 *
 * OpenAPI spec version: 1.0.7
 * Contact: api-support@testingtime.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "venue"
     */
    public function testPropertyVenue()
    {
    }

    /**
     * Test attribute "minutes"
     */
    public function testPropertyMinutes()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "quote"
     */
    public function testPropertyQuote()
    {
    }

    /**
     * Test attribute "incentive"
     */
    public function testPropertyIncentive()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "slots"
     */
    public function testPropertySlots()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "pool_secret"
     */
    public function testPropertyPoolSecret()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "nda"
     */
    public function testPropertyNda()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "languages_op"
     */
    public function testPropertyLanguagesOp()
    {
    }

    /**
     * Test attribute "min_age"
     */
    public function testPropertyMinAge()
    {
    }

    /**
     * Test attribute "max_age"
     */
    public function testPropertyMaxAge()
    {
    }

    /**
     * Test attribute "gender_mix"
     */
    public function testPropertyGenderMix()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "contact_via_type"
     */
    public function testPropertyContactViaType()
    {
    }

    /**
     * Test attribute "contact_via_details"
     */
    public function testPropertyContactViaDetails()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "devices"
     */
    public function testPropertyDevices()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "screening"
     */
    public function testPropertyScreening()
    {
    }
}
