<?php
/**
 * HandlingParticipantsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TestingTime Public API
 *
 * Partners API to recruit test users with TestingTime programmatically
 *
 * OpenAPI spec version: 1.0.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * HandlingParticipantsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HandlingParticipantsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for ordersOrderIdParticipantsGet
     *
     * Read all available & matching participants of an order..
     *
     */
    public function testOrdersOrderIdParticipantsGet()
    {
    }

    /**
     * Test case for ordersOrderIdParticipantsParticipantIdPut
     *
     * Assign and confirm a specific participant to a slot.
     *
     */
    public function testOrdersOrderIdParticipantsParticipantIdPut()
    {
    }

    /**
     * Test case for ordersOrderIdParticipantsParticipantIdRatingPost
     *
     * Rate a participant.
     *
     */
    public function testOrdersOrderIdParticipantsParticipantIdRatingPost()
    {
    }
}
